version: '3.8'

services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: ./elasticsearch/
    ports:
      - "9200:9200"
    environment:
      # elasticsearch maximun minimun heap size option
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - elk

  kibana:
    container_name: kibana
    build:
      context: ./kibana/
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  logstash:
    container_name: logstash
    build:
      context: ./logstash/
    ports:
      - "9600:9600"
    environment:
      # logstash maximun minimun heap size option
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk: