FROM docker.elastic.co/kibana/kibana:7.8.0

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>

# COPY configuration files
WORKDIR /usr/share/kibana
# COPY ./config/kibana.yml ./config/kibana.yml